import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <div className='header-wrapper'>
<div>
  <img src="/images/logo.png"></img>
</div>
<div className='right-header-wrapper'>
<div>
  <img src="/images/ho.png"></img>
</div>
<div>
  <img src="/images/crea.png"></img>
</div>
<div>
  <img src="/images/mycom.png"></img>
</div>
<div>
  <img src="/images/profile.svg"></img>
</div>
</div>
       </div>
       <div className='free-wrapper'>
        <div className='free'>Free</div>
        <div>Instagram Engagement Rate Calculator</div>  
        
        </div>
        <div className='try'>Try our free engagement  Rate Calculator to find out  the engagement  of any Instagram account</div>
        <div className='input-wrapper'>
          <div>
            <img src="/images/search.png"></img>
          </div>
          <div className='dropdown-wrapepr'>
            <img src="/images/drodown.png"></img>
          </div>
        
        </div>
        <div className='card-wrapper'>
          <div className='card'>
            <div className='green-back-warpper'>
<img className='green-back' src="/images/greens.png"></img>
            </div>
           
            <div className='people-wrapper'>
            <div  className='pback'>
              <img src="/images/pback.png"></img>
            </div>
            <div className='people'>
              <img src="/images/people.png"></img>
            </div>
            <div className='pcircle'>
              <img src="images/pcircle.png"></img>
            </div>
            </div>
            <div className='inner-card'>
            <div className='insta-wrapper'>
              <div>
                <img style={{height:"25px",width:"25px"}} src="/images/insta.svg"></img>
              </div>
              <div style={{fontSize:"22px"}}>mukeshneilnitin</div>
            </div>
            <div className='followers-wrapper'>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            </div>
            <div className='engegment-wrapper'>
            <div className='bold'>Engagment Rate</div>
            <div>
              <img src="/images/Twitter.png"></img>
            </div>
            
            </div>

            <div className='rainbow-wrapper'>
              <div>
<img src="/images/rainbowback.png"></img>
</div>
<div>
  <img className='rainbow-img' src="/images/rmeter.png"></img>
</div>
            </div>
            <div style={{fontSize:"22px",textAlign:"center"}} className='bold'>2.82%</div>
            <div className='login-wrapper'>
            <div >
            to get full report!
            </div>
            <div className='blue-login'> Login</div>
            </div>
          </div>
          </div>
          <div className='card'>
            <div className='green-back-warpper'>
<img className='green-back' src="/images/greens.png"></img>
            </div>
           
            <div className='people-wrapper'>
            <div  className='pback'>
              <img src="/images/pback.png"></img>
            </div>
            <div className='people'>
              <img src="/images/people.png"></img>
            </div>
            <div className='pcircle'>
              <img src="images/pcircle.png"></img>
            </div>
            </div>
            <div className='inner-card'>
            <div className='insta-wrapper'>
              <div>
                <img style={{height:"25px",width:"25px"}} src="/images/insta.svg"></img>
              </div>
              <div style={{fontSize:"22px"}}>mukeshneilnitin</div>
            </div>
            <div className='followers-wrapper'>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            <div className=''>
             <div className='one'>
              <div >
                <img src="/images/chat.png"></img>
              </div>  
              <div className='bold'>1.1 M</div>
              </div>
              <div>Followers</div>
            </div>
            </div>
            <div className='engegment-wrapper'>
            <div className='bold'>Engagment Rate</div>
            <div>
              <img src="/images/Twitter.png"></img>
            </div>
            </div>

            <div className='rainbow-wrapper'>
              <div>
<img src="/images/rainbowback.png"></img>
</div>
<div>
  <img className='rainbow-img' src="/images/rmeter.png"></img>
</div>
            </div>
            <div style={{fontSize:"22px",textAlign:"center"}} className='bold'>2.82%</div>
            <div className='login-wrapper'>
            <div >
            to get full report!
            </div>
            <div className='blue-login'> Login</div>
            </div>
          </div>
          </div>
        </div>
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
